### ISSUE TITLE
README.md gmcnn-place"s"2-tf

### ISSUE THREAD

**Issue by kobuworks** [yas-sim/interactive-image-inpainting#1]
Hi yas-sim san,
Thanks a lot for sharing great work, found a typo, demo itself worked successfully!
BR/Kobu
==================
gmcnn-place"s"2-tf

README.md
The demo expects the following models in the Intermediate Representation (IR) format:
gmcnn-place2-tf

**Comment by yas-sim** [comment]
Thanks Kobu-san as usual.
The name of the model has been corrected.
